alias bl_dock="cd bldock"
alias bl_mothership="cd $MOTHERSHIP"
alias bl_aleppo="cd $ALEPPO"
alias bl_sentinel="cd $SENTINEL"
alias bl_redline="cd $REDLINE"
alias bl_silkroad="cd $SILKROAD"
alias bl_bigmom="cd $BIGMOM"
alias bl_nitnit_server="cd $NITNIT"
alias bl_nitnit_job="cd $NITNIT"
alias bl_essos="cd $ESSOS"
alias bl_westeros="cd $WESTEROS"
alias bl_baseplate="cd $BASEPLATE"
alias bl_dora="cd $DORA"
alias bl_hahen="cd $HAHEN"
alias bl_opensesame="cd $OPENSESAME"

alias bl_workplace="cd $WORK"

alias runmysql="brew services run mysql@5.7"
